#pragma once

#include <SDL3/SDL_stdinc.h>

typedef enum shiny_theme_color_t: Uint8
{
	SHINY_COLOR_INVALID,

	SHINY_COLOR_FOREGROUND,
	SHINY_COLOR_WINDOW_BACKGROUND,
	SHINY_COLOR_WINDOW_HEADER,
	SHINY_COLOR_WINDOW_BORDER,
	SHINY_COLOR_CONTROL_BACKGROUND,
	SHINY_COLOR_CONTROL_HOVER,
	SHINY_COLOR_CONTROL_ACTIVE,
	SHINY_COLOR_CONTROL_CURSOR,
	SHINY_COLOR_CLEAR,
	SHINY_COLOR_BORDER,

	SHINY_COLOR_SIZE,
} shiny_theme_color_t;

typedef enum shiny_theme_gap_t: Uint8
{
	SHINY_GAP_INVALID,

	SHINY_GAP_DEFAULT,
	SHINY_GAP_MENUBAR,
	SHINY_GAP_WINDOW_ITEM,

	SHINY_GAP_SIZE,
} shiny_theme_gap_t;

typedef enum shiny_theme_corner_radius_t: Uint8
{
	SHINY_CORNER_RADIUS_INVALID,

	SHINY_CORNER_RADIUS_DEFAULT,
	SHINY_CORNER_RADIUS_WINDOW,
	SHINY_CORNER_RADIUS_CONTROL,

	SHINY_CORNER_RADIUS_SIZE,
} shiny_theme_corner_radius_t;

typedef enum shiny_theme_padding_t: Uint8
{
	SHINY_PADDING_INVALID,

	SHINY_PADDING_MENUBAR,
	SHINY_PADDING_MENU_ITEM,
	SHINY_PADDING_WINDOW_HEADER_Y,
	SHINY_PADDING_WINDOW_HEADER_X,
	SHINY_PADDING_WINDOW_CONTENT,
	SHINY_PADDING_CONTROL,
	SHINY_PADDING_COMBOBOX,

	SHINY_PADDING_SIZE,
} shiny_theme_padding_t;

typedef enum shiny_theme_size_t: Uint8
{
	SHINY_SIZE_INVALID,

	SHINY_WIDTH_COMBOBOX,
	SHINY_HEIGHT_COMBOBOX,

	SHINY_SIZE_SIZE,
} shiny_theme_size_t;
